PUT /players/2769e215-d4cd-4532-84e0-fac4ad34ac6e/update_image HTTP/1.1
Host: localhost:3000
Authorization: Bearer e04b6f16-11e8-4c09-ad9e-24466b7ec971
Content-Length: 187
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image
"; filename="Perfil_LS.jpg"
Content-Type: image/jpeg

"CardGameRuby/public/images/cards/blue/0.png"
------WebKitFormBoundary7MA4YWxkTrZu0gW--






"CardGameRuby/public/images/cards/blue/0.png"
"CardGameRuby/public/images/null_profile.png"

