PUT /players/4c4ed93d-9ea5-4f2e-a47a-5f6cce3ed836/update_image HTTP/1.1
Host: localhost:3000
Authorization: Bearer 4fb3c343-5a7b-48e5-9b94-1b9600356908
Content-Length: 188
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Portada_TB.jpg"
Content-Type: image/jpeg

/home/lucasm/Pictures/Perfil_LS.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--






/home/lucasm/Pictures/Gorillaz/441368.jpg

/home/lucasm/Pictures/Perfil_LS.jpg

CardGameRuby/public/images/cards/blue/0.png
CardGameRuby/public/images/null_profile.png

